export { default as Home } from './Home'
export { default as ProfilePage } from './ProfilePage'
export { default as AdminPage } from './admin/AdminPage'
export { default as LoginPage } from './LoginPage'
export { default as Register } from './Register'
export { default as StaffPage } from './staff/StaffPage'
export { default as Report } from './staff/Report'
export { default as Userlist } from './staff/Userlist'
export { default as TicketApproval } from './staff/TicketApproval'
export { default as ChangePassword } from './ChangePassword'
export { default as ResetPassword } from './ResetPassword'
export { default as TicketDetailPage } from './TicketDetailPage'
export { default as CreateTicketPage } from './CreateTicketPage'
export { default as Chat } from './Chat'
//admin
export { default as ManagerUsers } from './admin/ManagerUser'
export { default as ManagerTicket } from './admin/ManagerTicket'
export { default as blog } from './BlogPage'
export { default as subscriptions } from './Subscriptions'
export { default as transactions } from './admin/Transactions'

//user
export { default as MembershipPage } from './MembershipPage'
export { default as allTickets } from './ViewAllTicketPage'
export { default as success } from './error/SuccessPage'
export { default as fail } from './error/FailPage'
export { default as YourTicket } from './YourTicketPage'
export { default as ManageMyTicketPage } from './ManageMyTicketPage'
