export { default as Home } from './Home'
export { default as ProfilePage } from './ProfilePage'
export { default as AdminPage } from './admin/AdminPage'
export { default as LoginPage } from './LoginPage'
export { default as Register } from './Register'
