name: Deploy on VPS

on: 
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use github secrets
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_MOCK_API_URL=${{ secrets.VITE_MOCK_API_URL }}" >> .env
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env

          echo "VITE_CHAT_APP_API_KEY=${{ secrets.VITE_CHAT_APP_API_KEY }}" >> .env
          echo "VITE_CHAT_APP_AUTH_DOMAIN=${{ secrets.VITE_CHAT_APP_AUTH_DOMAIN }}" >> .env
          echo "VITE_CHAT_APP_PROJECT_ID=${{ secrets.VITE_CHAT_APP_PROJECT_ID }}" >> .env
          echo "VITE_CHAT_APP_STORAGE_BUCKET=${{ secrets.VITE_CHAT_APP_STORAGE_BUCKET }}" >> .env
          echo "VITE_CHAT_APP_MESSAGING_SENDER_ID=${{ secrets.VITE_CHAT_APP_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_CHAT_APP_APP_ID=${{ secrets.VITE_CHAT_APP_APP_ID }}" >> .env
          echo "VITE_CHAT_APP_MEASUREMENT_ID=${{ secrets.VITE_CHAT_APP_MEASUREMENT_ID }}" >> .env
        shell: bash

      - name: Compose down
        run: docker compose down
        shell: bash

      - name: Run `docker compose`
        run: docker compose up --build -d
        shell: bash 

      - name: Remove unused images
        run: docker system prune -a -f
        shell: bash
