name: Deploy on VPS

on: 
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use github secrets
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_MOCK_API_URL=${{ secrets.VITE_MOCK_API_URL }}" >> .env
        shell: bash

      - name: Compose down
        run: |
          docker compose down
        shell: bash

      - name: Run `docker compose`
        run: |
          docker compose up --build -d
        shell: bash 